version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - nexmind-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    networks:
      - nexmind-network
    restart: unless-stopped

  # Database Service (可选，如果使用PostgreSQL)
  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: nexmind
  #     POSTGRES_USER: nexmind
  #     POSTGRES_PASSWORD: nexmind_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - nexmind-network

  # Redis Service (可选，用于缓存)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - nexmind-network

networks:
  nexmind-network:
    driver: bridge

volumes:
  # postgres_data:
  # redis_data:
  node_modules: